modLoader="kotlinforforge"
loaderVersion="[1,)"
[[mods]]
modId="lavafurnacemod"
version="${version}"
displayName="Lava Furnace"
authors="prc94"
description='''
Lava Furnace
Place a lava block beneath it to make it run.
Crafted just like normal furnace, but from 8 obsidian instead of cobblestone.
'''
[[dependencies.lavafurnacemod]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lavafurnacemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
